org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1
fabric_kotlin_version=1.13.7+kotlin.2.2.21
mod_menu_version=11.0.4

mod_version=0.1.0
maven_group=dev.freelocs.aetherion
archives_base_name=aetherion
